pipeline:
    name: Main Build
    identifier: Main_Build
    allowStageExecutions: false
    stages:
        - stage:
              name: Python Build
              identifier: Build
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: konrse_GKE_Bank_of_Harness
                          namespace: bankofharness-builds
                          automountServiceAccountToken: true
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: Python Build
                                identifier: pythonbuild
                                spec:
                                    connectorRef: Docker_Hub_Konr
                                    image: python:3.8
                                    shell: Sh
                                    command: |
                                        echo "testing $SERVICE..."

                                        cd src/$SERVICE

                                        pip install --upgrade pip
                                        pip install -r requirements.txt
                                        python -m pytest -v -p no:warnings --junitxml=report.xml
                                    reports:
                                        type: JUnit
                                        spec:
                                            paths:
                                                - src/contacts/report.xml
                                    envVariables:
                                        SERVICE: <+input>
                                failureStrategies: []
              variables:
                  - name: service
                    type: String
                    value: contacts
    projectIdentifier: Bank_of_Harness
    orgIdentifier: default
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: konrnessbankofharness
                build: <+input>
