pipeline:
    name: Main Build
    identifier: Main_Build
    allowStageExecutions: false
    stages:
        - stage:
              name: Clone
              identifier: Clone
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: konrse_GKE_Bank_of_Harness
                          namespace: bankofharness-builds
                          automountServiceAccountToken: false
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: ls
                                identifier: ls
                                spec:
                                    connectorRef: Docker_Hub_Konr
                                    image: alpine
                                    shell: Sh
                                    command: ls
        - parallel:
              - stage:
                    name: Contacts - Build
                    identifier: Build
                    template:
                        templateRef: Python_Build
                        versionLabel: "1"
                        templateInputs:
                            type: CI
                            variables:
                                - name: service
                                  type: String
                                  value: contacts
              - stage:
                    name: User Service - Build
                    identifier: User_Service_Build
                    template:
                        templateRef: Python_Build
                        versionLabel: "1"
                        templateInputs:
                            type: CI
                            variables:
                                - name: service
                                  type: String
                                  value: userservice
              - stage:
                    name: Frontend - Build
                    identifier: Frontend_Build
                    template:
                        templateRef: Python_Build
                        versionLabel: "1"
                        templateInputs:
                            type: CI
                            variables:
                                - name: service
                                  type: String
                                  value: frontend
    projectIdentifier: Bank_of_Harness
    orgIdentifier: default
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: konrnessbankofharness
                build: <+input>
