pipeline:
    name: Main Build
    identifier: Main_Build
    allowStageExecutions: false
    stages:
        - stage:
              name: "Build "
              identifier: Build
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: konrse_GKE_Bank_of_Harness
                          namespace: bankofharness-builds
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: ls
                                identifier: ls
                                spec:
                                    connectorRef: Docker_Hub_Konr
                                    image: alpine
                                    shell: Sh
                                    command: ls
    projectIdentifier: Bank_of_Harness
    orgIdentifier: default
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: konrnessbankofharness
                build: <+input>
