pipeline:
    name: Main Build
    identifier: Main_Build
    allowStageExecutions: false
    stages:
        - stage:
              name: Clone
              identifier: Clone
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: konrse_GKE_Bank_of_Harness
                          namespace: bankofharness-builds
                          volumes:
                              - mountPath: /root/.m2
                                type: HostPath
                                spec:
                                    path: /tmp/.m2
                                    type: DirectoryOrCreate
                          automountServiceAccountToken: false
                          nodeSelector: {}
                          os: Linux
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: ls
                                identifier: ls
                                spec:
                                    connectorRef: Docker_Hub_Konr
                                    image: alpine
                                    shell: Sh
                                    command: ls
                  sharedPaths:
                      - ""
              when:
                  pipelineStatus: Success
                  condition: true == false
              variables: []
        - parallel:
              - stage:
                    name: Contacts - Build
                    identifier: Contacts_Build
                    template:
                        templateRef: Python_Build
                        versionLabel: "1"
                        templateInputs:
                            type: CI
                            variables:
                                - name: service
                                  type: String
                                  value: contacts
                                - name: runTests
                                  type: String
                                  value: "true"
              - stage:
                    name: User Service - Build
                    identifier: User_Service_Build
                    template:
                        templateRef: Python_Build
                        versionLabel: "1"
                        templateInputs:
                            type: CI
                            variables:
                                - name: service
                                  type: String
                                  value: userservice
                                - name: runTests
                                  type: String
                                  value: "true"
              - stage:
                    name: Frontend - Build
                    identifier: Frontend_Build
                    template:
                        templateRef: Python_Build
                        versionLabel: "1"
                        templateInputs:
                            type: CI
                            variables:
                                - name: service
                                  type: String
                                  value: frontend
                                - name: runTests
                                  type: String
                                  value: "false"
        - parallel:
              - stage:
                    name: Balance Reader - Build
                    identifier: Balance_Reader_Build
                    template:
                        templateRef: Java_Build
                        versionLabel: "1"
                        templateInputs:
                            type: CI
                            variables:
                                - name: service
                                  type: String
                                  value: balancereader
              - stage:
                    name: Ledger Writer - Build
                    identifier: Ledger_Writer_Build
                    template:
                        templateRef: Java_Build
                        versionLabel: "1"
                        templateInputs:
                            type: CI
                            variables:
                                - name: service
                                  type: String
                                  value: ledgerwriter
        - stage:
              name: Accounts DB - Build
              identifier: Accounts_DB_Build
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      useFromStage: Clone
                  execution:
                      steps:
                          - step:
                                type: BuildAndPushDockerRegistry
                                name: Docker Build and Push
                                identifier: Docker_Build_and_Push
                                spec:
                                    connectorRef: Docker_Hub_Konr
                                    repo: konrness/bank-of-harness-accounts-db
                                    tags:
                                        - <+pipeline.sequenceId>
                                    context: src/accounts-db
                                    labels:
                                        pipeline: <+pipeline.name>
                                        build_url: https://app.harness.io/ng/#/account/6C9qo5gJSdK7gb-ngOtpCw/ci/orgs/default/projects/Bank_of_Harness/pipelines/Main_Build/executions/<+pipeline.executionId>/pipeline
    projectIdentifier: Bank_of_Harness
    orgIdentifier: default
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: konrnessbankofharness
                build: <+input>
