pipeline:
    name: Main Build
    identifier: Main_Build
    allowStageExecutions: false
    stages:
        - parallel:
              - stage:
                    name: Contacts - Build
                    identifier: Build
                    template:
                        templateRef: Python_Build
                        versionLabel: "1"
                        templateInputs:
                            type: CI
                            variables:
                                - name: service
                                  type: String
                                  value: contacts
              - stage:
                    name: User Service - Build
                    identifier: User_Service_Build
                    template:
                        templateRef: Python_Build
                        versionLabel: "1"
                        templateInputs:
                            type: CI
                            variables:
                                - name: service
                                  type: String
                                  value: userservice
    projectIdentifier: Bank_of_Harness
    orgIdentifier: default
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: konrnessbankofharness
                build: <+input>
