pipeline:
    name: Main Build
    identifier: Main_Build
    allowStageExecutions: false
    stages:
        - stage:
              name: Contacts - Build
              identifier: Build
              template:
                  templateRef: Python_Build
                  versionLabel: "1"
    projectIdentifier: Bank_of_Harness
    orgIdentifier: default
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: konrnessbankofharness
                build: <+input>
